
#logging:
#  level:
#    org:
#      springframework:
#        beans: debug
#        context: debug
#      hibernate:
#        type:
#          descriptor:
 #           sql: trace

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle19cDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
        
#    defer-datasource-initialization: true   
##   sql\ucd08\uae30\ud654  
#  sql:
#    init:
#      mode: always
#      data-locations:
#      - classpath:static/erd/insert.sql
#      continue-on-error: true
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true